1_Wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    # Pass title to wiki function to read markdown file
    path("wiki/<str:title>", views.wiki, name="wiki"),
    # Url for random encyclopedia entry
    path("random/", views.random_entry, name="random"),
    # Url for creating new encyclopedia entry
    path("newentry/", views.new_entry, name="newentry"),
    # Url for editing encyclopedia entry
    path("edit/<str:title>", views.edit_entry, name="editentry")
]

1_Wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

1_Wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

1_Wiki/encyclopedia/views.py
from random import choice
from markdown2 import Markdown
from django import forms
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from . import util


def index(request):
    """
    Show list of encyclopedia entries, filtered by search queries
    """
    # Get query from search
    query = request.GET.get('q', '')
    # If text was present in search
    if not query == '':
        # Get full list of entries
        full_list = util.list_entries()
        filtered_list = []
        # Iterate through list of entries
        for title in full_list:
            # If query matches name of entry, redirect user to entry page
            if title == query:
                return wiki(request, title)
            # Add enclopedia entries with query as substring to filtered list
            if query in title:
                filtered_list.append(title)
        # Return list of filtered titles if no exact match found
        return render(request, "encyclopedia/index.html", {
            "entries": filtered_list,
            "heading": "Pages Found"
        })
    # Return full list of entries if no search performed
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "heading": "All Pages"
    })


def wiki(request, title):
    """
    Renders encyclopedia entries to html page
    """
    # Read markdown file
    md_file = util.get_entry(title)
    if md_file is None:
        # Return error page with requested title
        return render(request, "encyclopedia/error.html", {
            "title": title
        })
    # Convert markdown to html and send data to template
    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "entry": Markdown().convert(md_file)
    })


def random_entry(request):
    """
    Renders random encyclopedia entry
    """
    # Get random encyclopedia entry
    random_entry = choice(util.list_entries())
    return wiki(request, random_entry)


class new_entry_form(forms.Form):
    """
    Django new entry form, inherits from forms.Form
    """
    title = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}), label="Title")
    content = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control"}), label="Content")


def new_entry(request):
    """
    Create new encyclopedia entry
    """
    # If new entry being submitted
    if request.method == "POST":
        form = new_entry_form(request.POST)
        # Check for valid input
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            # Add markdown title to content, add newline before and after content
            content = f"# {title}\n\n{content}\n"
            # If entry exists, present error message
            if util.get_entry(title):
                messages.error(request, "Error: Page already exists")
                # Send back existing form data
                return render(request, "encyclopedia/newentry.html", {
                    "form": form
                })
            # Save entry to disk and take user to new entry's page
            else:
                util.save_entry(title, content)
                return HttpResponseRedirect(reverse("encyclopedia:wiki", args=[title]))
        # Invalid input, send back existing form data
        else:
            return render(request, "encyclopedia/newentry.html", {
                "form": form
            })
    # Render empty form if received get request
    return render(request, "encyclopedia/newentry.html", {
        "form": new_entry_form()
    })


class edit_entry_form(forms.Form):
    """
    Django edit entry form, inherits from forms.Form
    """
    content = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control"}), label="Content")


def edit_entry(request, title):
    """
    Edit encyclopedia entry
    """
    # Read markdown file
    md_file = util.get_entry(title)
    if md_file is None:
        # Return error page with requested title
        return render(request, "encyclopedia/error.html", {
            "title": title
        })

    # Split markdown file into title and content
    md_partition = md_file.partition('\n')
    # Get first line from markdown file
    first_line = md_partition[0]
    # Remove first two characters (markdown heading)
    heading = first_line[2:]
    # Content is in partition after newline
    content_section = md_partition[2]
    # Get page content from markdown file by removing first and last lines
    content = '\n'.join(content_section.split('\n')[1:-1])

    # If edited entry being submitted
    if request.method == "POST":
        form = edit_entry_form(request.POST)
        # Check for valid input
        if form.is_valid():
            content = form.cleaned_data["content"]
            # Add markdown title to content, add newline before and after content
            content = f"# {heading}\n\n{content}\n"
            # Save entry to disk and take user to new entry's page
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse("encyclopedia:wiki", args=[title]))
        # Invalid input, send back existing form data
        else:
            return render(request, "encyclopedia/editentry.html", {
                "title": title,
                "heading": heading,
                "form": form 
            })
    # Populate form with encyclopedia entry content
    return render(request, "encyclopedia/editentry.html", {
        "title": title,
        "heading": heading,
        "form": edit_entry_form(initial={"content": content})
    })

1_Wiki/encyclopedia/templates/encyclopedia/editentry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-10">
            <h1>{{ heading }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-10">
            <form action="{% url 'encyclopedia:editentry' title=title %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    {{ form }}
                </div>
                <a href="{% url 'encyclopedia:wiki' title=title %}" class="btn
                btn-default">Cancel</a>
                <input type="submit" class="btn btn-primary float-right"
                value="Save Changes">
            </form>
        </div>
    </div>
</div>

{% endblock %}

1_Wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    {{ entry|safe }}
    <a href="{% url 'encyclopedia:editentry' title=title %}" class="btn btn-primary">Edit Page</a>
{% endblock %}

1_Wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <!-- <h1>Error: {{ title }} Not Found</h1> -->
    <div class="container">
        <div class="row">
            <div class="col-10 text-center">
                <h1 class="display-1 d-block">404</h1>
                <div class="mb-4 lead">The page <span class="badge">{{ title }}</span> was not found.</div>
                <a href="{% url 'encyclopedia:index' %}" class="btn btn-link">Back to Home</a>
            </div>
        </div>
    </div>

{% endblock %}

1_Wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>{{ heading }}</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:wiki' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

1_Wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:index' %}">
                    <input class="search form-control mr-sm-2" type="search" name="q" placeholder="Search Encyclopedia">
                    <button type="submit" class="btn btn-outline-primary my-2 my-sm-0">Search</button>
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newentry' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

1_Wiki/encyclopedia/templates/encyclopedia/newentry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-10">
            <h1>Create New Page</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-10">
            {% if messages %}
            {% for message in messages %}
                <div class="alert alert-danger" role="alert">
                        {{ message }}
                </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-10">
            <form action="{% url 'encyclopedia:newentry' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    {{ form }}
                </div>
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>

{% endblock %}