2_Commerce/auctions/urls.py
from django.urls import path

from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = "auctions"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("new_listing/", views.new_listing, name="new_listing"),
    path("listing/<int:listing_id>", views.listing, name="listing"),
    path("listing/<int:listing_id>/watch", views.watch, name="watch"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("categories", views.categories, name="categories"),
    path("categories/<int:category_id>", views.category, name="category"),
    path("listing/<int:listing_id>/close", views.close_listing, name="close_listing")
]

# Make image url accessible
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

2_Commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

2_Commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

    def __str__(self):
        return f"{self.id} {self.username} {self.first_name}"

# Allow listings to be sorted by category
class Category(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.name}"

# Model for auction listing
class Listing(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="listings")
    title = models.CharField(max_length=64)
    description = models.TextField()
    image = models.ImageField(null=True, blank=True, upload_to="auctions")
    category = models.ForeignKey(Category, blank=True, on_delete=models.CASCADE, related_name="category_items")
    date_created = models.DateTimeField()
    is_active = models.BooleanField()
    price = models.DecimalField(max_digits=19, decimal_places=2)
    highest_bid = models.ForeignKey('Bid', null=True, blank=True, on_delete=models.CASCADE, related_name="winners")
    watchers = models.ManyToManyField(User, blank=True, related_name="watchlist")
    
    def __str__(self):
        return f"{self.id} {self.creator.username} {self.title} {self.is_active} {self.price}"

# Model for bids
class Bid(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_bids")
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="listing_bids")
    price = models.DecimalField(max_digits=19, decimal_places=2)
    date = models.DateTimeField()

    def __str__(self):
        return f"{self.id} {self.user.username} {self.listing} {self.price}"

# Model for comments made on auction listings
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="listing_comments")
    comment = models.TextField()
    date = models.DateTimeField()

    def __str__(self):
        return f"{self.id} {self.user.username} {self.listing.id} {self.comment}"

2_Commerce/auctions/forms.py
from django import forms
from .models import Category, Listing, Bid, Comment


class NewCategoryForm(forms.ModelForm):
    """
    New category form from category model
    """
    class Meta:
        model = Category
        fields = ['name']
        # Add classes for bootstrap styling
        # Add list for datalist input
        widgets = {
            'name': forms.TextInput(attrs={"class": "form-control", "list": "categories"})
        }
        labels = {
            'name': "Category"
        }


class NewListingForm(forms.ModelForm):
    """
    New listing form from listing model
    """
    class Meta:
        model = Listing
        fields = ['title', 'description', 'price', 'image']
        # Add classes for bootstrap styling
        widgets = {
            'title': forms.TextInput(attrs={"class": "form-control"}),
            'description': forms.Textarea(attrs={"class": "form-control", "rows": "5"}),
            'price': forms.NumberInput(attrs={"class": "form-control"}),
            'image': forms.FileInput(attrs={"class": "form-control"})
        }


class NewBidForm(forms.ModelForm):
    """
    New bid form from bid model
    """
    class Meta:
        model = Bid
        fields = ['price']
        # Add classes for bootstrap styling
        widgets = {
            'price': forms.NumberInput(attrs={"class": "form-control", "placeholder": "Bid"})
        }
        labels = {
            'price': "Enter bid here:"
        }


class NewCommentForm(forms.ModelForm):
    """
    New comment form from comment model
    """
    class Meta:
        model = Comment
        fields = ['comment']
        # Add classes for bootstrap styling
        widgets = {
            'comment': forms.Textarea(attrs={
                "class": "form-control",
                "placeholder": "Add a public comment...",
                "rows": "5"
            }),
        }
        # Hide comment label
        labels = {
            'comment': ""
        }

2_Commerce/auctions/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.db.models import Count, Sum, Case, When, IntegerField
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .models import User, Listing, Category, Comment
from .forms import NewCategoryForm, NewListingForm, NewBidForm, NewCommentForm


def index(request):
    # Show active listings on homepage
    return render(request, "auctions/index.html", {
        "listings": Listing.objects.all(),
        "title": "Active Listings",
        "empty": "No active listings to display",
        "show_inactive": False
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")


# View for creating new listing
@login_required
def new_listing(request):
    all_categories = Category.objects.all
    # Load forms
    listing_form = NewListingForm()
    category_form = NewCategoryForm()
    context = {
        "listing_form": listing_form,
        "category_form": category_form,
        "all_categories": all_categories
    }
    if request.method == "POST":
        # Split form data by model attributes
        category_keys = ["name"]
        listing_keys = ["title", "description", "price"]
        # Function to split data into separate dictionaries based on keys
        filter_by_key = lambda keys: {x: request.POST[x] for x in keys}
        category_data = filter_by_key(category_keys)
        listing_data = filter_by_key(listing_keys)
        # Get category id if category exists, compare using TitleCase
        category_input = category_data["name"].title()
        category = Category.objects.filter(name=category_input).first()
        # No match found, create new category
        if category is None:
            category_data["name"] = category_input
            category_form = NewCategoryForm(category_data)
            # If category form data is valid, create new category and add it to
            # listing form data
            if category_form.is_valid():
                category = category_form.save()
            else:
                messages.error(request, "Error: could not create category")
                return render(request, "auctions/newlisting.html", context)
        # Check if listing form data is valid, pass in image file
        listing_form = NewListingForm(listing_data, request.FILES)
        if listing_form.is_valid():
            new_listing_object = listing_form.save(commit=False)
            # Autofill attributes of new listing objects
            new_listing_object.creator = request.user
            new_listing_object.category = category
            new_listing_object.date_created = datetime.now()
            new_listing_object.is_active = True
            new_listing_object.save()
            messages.success(request, "New listing has been created")
            return HttpResponseRedirect(reverse("auctions:listing", args=[new_listing_object.id]))
        else:
            messages.error(request, "Error: could not create listing")
            return render(request, "auctions/newlisting.html", context)
    return render(request, "auctions/newlisting.html", context)


# View for each individual listing
def listing(request, listing_id):
    # Return 404 page if listing not found
    listing_obj = get_object_or_404(Listing, pk=listing_id)
    # Get bid form and pass it to html template
    bid_form = NewBidForm()
    bidder_count = listing_obj.listing_bids.count()
    # Get information about highest bid
    highest_bid = listing_obj.highest_bid
    highest_bidder = None
    highest_bid_price = None
    if highest_bid:
        highest_bidder = highest_bid.user
        highest_bid_price = highest_bid.price
    # Check if listing is part of user's watchlist
    watching = False
    if request.user.is_authenticated and request.user.watchlist.filter(pk=listing_id):
        watching = True
    # Get comment data and pass it to html template
    listing_comments = listing_obj.listing_comments.all()
    # Get comment form and pass it to html template
    comment_form = NewCommentForm()
    # Check that user is creator of listing
    is_creator = False
    if request.user == listing_obj.creator:
        is_creator = True
    context = {
        "listing": listing_obj,
        "bid_form": bid_form,
        "bidder_count": bidder_count,
        "highest_bidder": highest_bidder,
        "highest_bid_price": highest_bid_price,
        "watching": watching,
        "comment_form": comment_form,
        "listing_comments": listing_comments,
        "is_creator": is_creator
    }
    if request.method == "POST":
        # Check if bid form received
        if "price" in request.POST:
            bid_form = NewBidForm(request.POST)
            # Check bid form data is valid
            if bid_form.is_valid():
                # Make sure bid price is higher than current bid
                bid_price = bid_form.cleaned_data["price"]
                min_bid = listing_obj.price
                # Compare to starting price if no bid placed yet
                if listing_obj.highest_bid:
                    min_bid = listing_obj.highest_bid.price
                if bid_price <= min_bid:
                    messages.error(request, "Error: bid must be higher than current price")
                    return render(request, "auctions/listing.html", context)
                # Bid is valid, autofill attributes then save new bid
                new_bid_object = bid_form.save(commit=False)
                new_bid_object.user = request.user
                new_bid_object.listing = listing_obj
                new_bid_object.date = datetime.now()
                new_bid_object.save()
                # Update highest bid on listing object
                listing_obj.highest_bid = new_bid_object
                listing_obj.save()
                messages.success(request, "Your bid has been accepted")
                return HttpResponseRedirect(reverse("auctions:listing", args=[listing_id]))
            else:
                messages.error(request, "Error: invalid bid")
                return render(request, "auctions/listing.html", context)
        # Check if comment form received
        elif "comment" in request.POST:
            comment_form = NewCommentForm(request.POST)
            # Check comment form data is valid
            if comment_form.is_valid():
                # Comment is valid, autofill attributes then save new comment
                new_comment_object = comment_form.save(commit=False)
                new_comment_object.user = request.user
                new_comment_object.listing = listing_obj
                new_comment_object.date = datetime.now()
                new_comment_object.save()
                messages.success(request, "Your comment has been posted")
                return HttpResponseRedirect(reverse("auctions:listing", args=[listing_id]))
            else:
                messages.error(request, "Error: invalid comment")
                return render(request, "auctions/listing.html", context)
    return render(request, "auctions/listing.html", context)


# Add or remove from watchlist
@login_required
def watch(request, listing_id):
    # Return 404 page if listing not found
    listing_obj = get_object_or_404(Listing, pk=listing_id)
    # Remove listing if found in watchlist
    watchlisting = request.user.watchlist.filter(pk=listing_id).first()
    if watchlisting:
        request.user.watchlist.remove(watchlisting)
        messages.success(request, "Item has been removed from watchlist")
    else:
        # Add to watchlist if not already added
        request.user.watchlist.add(listing_obj)
        messages.success(request, "Item has been added to watchlist")
    return listing(request, listing_id)


# Show all listings from user's watchlist
@login_required
def watchlist(request):
    watchlistings = request.user.watchlist.all()
    context = {
        "listings": watchlistings,
        "title": "Watchlist",
        "empty": "Your watchlist is empty",
        "show_inactive": True
    }
    return render(request, "auctions/index.html", context)


# List all categories of listings

2_Commerce/auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-10">
          <h1 class="h2 mt-3">Categories</h1>
          <hr class="mt-1">
        </div>
      </div>
      <div class="row justify-content-center">
      {% if categories %}
        <div class="col-lg-6 col-md-9">
          <div class="list-group">
          {% for category in categories %}
            <a href="{% url 'auctions:category' category_id=category.id %}" class="list-group-item list-group-item-action d-flex
            justify-content-between align-items-center">
              {{ category.name }}
              <span class="badge badge-primary badge-pill">{{ category.num_items }}</span>
            </a>
          {% endfor %}
          </div>
        </div>
      {% else %}
        <div class="col-lg-10 mt-3 mb-2">
          <p class="text-center">No categories to display</p>
        </div>
      {% endif %}
      </div>
    </div>
{% endblock %}

2_Commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a href="{% url 'auctions:index' %}" class="navbar-brand">Auctions</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
                </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:watchlist' %}">Watchlist
                    <span class="badge badge-primary badge-pill">{{ user.watchlist.count }}</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:new_listing' %}">Create Listing</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <span class="navbar-text">
                    Signed in as <strong>{{ user.username }}</strong>.
                </span>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
            </ul>
            {% else %}
            </ul>
            <ul class="navbar-nav ml-auto">
                <span class="navbar-text">
                    Not signed in.
                </span>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
            </ul>
            {% endif %}
            </div>
        </nav>
        <hr class="mt-0">
        {% block body %}
        {% endblock %}
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

2_Commerce/auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-10">
          <h1 class="h2 mt-3">{{ listing.title }}</h1>
          <hr class="mt-1">
        </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-lg-10">
        {% if messages %} {% for message in messages %}
        {% if message.tags == "error" %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {% elif message.tags == "success" %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
        {% else %}
        <div class="alert alert-info alert-dismissible fade show" role="alert">
        {% endif %}
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %} {% endif %}
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-lg-10">
        <div class="row">
          <div class="col-lg-6 d-flex justify-content-center">
            {% if listing.image %}
            <img src="{{ listing.image.url }}" alt="{{ listing.title }}"
            class="img-thumbnail size-400">
            {% endif %}
          </div>
          <div class="col">
            <h3>Description</h3>
            <p>{{ listing.description }}</p>
            <p class="text-secondary"><small>Created {{ listing.date_created }}</small></p>
            {% if listing.is_active %}
            <div class="row">
              <div class="col">
                <h2>$
                  {% if listing.highest_bid %}
                  {{ listing.highest_bid.price }}
                  {% else %}
                  {{ listing.price }}
                  {% endif %}
                </h2>
                <p>
                  {{ bidder_count }}
                  {% if bidder_count == 1 %}
                    bid
                  {% else %}
                    bids
                  {% endif %}
                    so far.
                </p>
                <p>
                  {% if highest_bidder %}
                    {% if highest_bidder.id == user.id %}
                    Your
                    {% else %}
                    <span class="text-primary">{{ highest_bidder.username }}'s</span>
                    {% endif %}
                      bid is the the current bid.
                  {% endif %}
                </p>
              </div>
              {% if user.is_authenticated %}
                <div class="col-md-6 pb-2">
                  <form action="{% url 'auctions:listing' listing_id=listing.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ bid_form }}
                    </div>
                    <input type="submit" class="btn btn-primary btn-block" value="Place Bid">
                  </form>
                  <a href="{% url 'auctions:watch' listing_id=listing.id %}"
                  class="btn btn-light btn-block mt-2">
                    {% if watching %}
                    Remove from
                    {% else %}
                    Add to
                    {% endif %}
                    watchlist
                  </a>
                    {% if is_creator %}
                    <a href="{% url 'auctions:close_listing' listing_id=listing.id %}"
                    class="btn btn-danger btn-block">Close Listing</a>
                    {% endif %}
                </div>
              {% endif %}
            </div>
            {% else %}
            <div class="row">
              <div class="col">
                <h2>$
                  {% if listing.highest_bid %}
                  {{ listing.highest_bid.price }}
                  {% else %}
                  {{ listing.price }}
                  {% endif %}
                </h2>
                <p>
                  {{ bidder_count }}
                  {% if bidder_count == 1 %}
                    bid.
                  {% else %}
                    bids.
                  {% endif %}
                  {% if highest_bidder %}
                    {% if highest_bidder.id == user.id %}
                    Your
                    {% else %}
                    <span class="text-primary">{{ highest_bidder.username }}</span>'s
                    {% endif %}
                      bid is the the winning bid.
                  {% endif %}
                </p>
              </div>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-lg-10">
      <hr>
        <h3>Details</h3>
          <ul>
            <li>Listed by: <span class="text-primary">{{ listing.creator.username }}</span></li>
            <li>Category: {{ listing.category.name }}</li>
          </ul>
      </div>
    </div>
    <div class="row justify-content-center mb-5">
      <div class="col-lg-10">
      <hr>
      <h3>Comments</h3>
      {% if listing_comments %}
        {% for comment in listing_comments %}
      <div class="card mb-4">
        <div class="card-body">
          <p class="card-text">{{ comment.comment }}</p>
          <p class="text-secondary text-right mb-0"><small>By
          <span class="text-primary">
            {{ comment.user.username }}
          </span>
            at {{ comment.date }}</small></p>
        </div>
      </div>
        {% endfor %}
      {% else %}
      <p class="text-secondary">No comments on this listing.</p>
      {% endif %}
      {% if user.is_authenticated and listing.is_active %}
      <form action="{% url 'auctions:listing' listing_id=listing.id %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          {{ comment_form }}
        </div>
        <input type="submit" class="btn btn-primary" value="Post Comment">
      </form>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

2_Commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %} {% block body %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-10">
      <h1 class="h2 mt-3">Login</h1>
      <hr class="mt-1">
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-lg-10">
      {% if message %}
      <div class="alert alert-danger" role="alert">{{ message }}</div>
      {% endif %}
    </div>
  </div>
  <div class="row justify-content-center mt-3">
    <div class="col-lg-6 col-md-9">
      <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
          <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
      </form>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-9 mt-3 mb-2">
      <p class="text-center">Don't have an account? <a href="{% url 'auctions:register' %}">Register
    here.</a></p>
    </div>
  </div>
</div>
{% endblock %}

2_Commerce/auctions/templates/auctions/newlisting.html
{% extends "auctions/layout.html" %} {% block body %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-10">
      <h1 class="h2 mt-3">Create New Listing</h1>
      <hr class="mt-1">
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-lg-10">
      {% if messages %} {% for message in messages %}
      {% if message.tags == "error" %}
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
      {% elif message.tags == "success" %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
      {% else %}
      <div class="alert alert-info alert-dismissible fade show" role="alert">
      {% endif %}
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %} {% endif %}
    </div>
  </div>
  <div class="row justify-content-center mt-3">
    <div class="col-lg-6 col-md-9">
      <form action="{% url 'auctions:new_listing' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          {{ listing_form }} {{ category_form }}
          <datalist id="categories">
            {% for category in all_categories %}
              <option value="{{ category.name }}">
            {% endfor %}
          </datalist>
        </div>
        <input type="submit" class="btn btn-primary">
      </form>
    </div>
  </div>
</div>
{% endblock %}

2_Commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %} {% block body %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-10">
      <h1 class="h2 mt-3">Register</h1>
      <hr class="mt-1">
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-lg-10">
      {% if message %}
      <div class="alert alert-danger" role="alert">{{ message }}</div>
      {% endif %}
    </div>
  </div>
  <div class="row justify-content-center mt-3">
    <div class="col-lg-6 col-md-9">
      <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
          <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
          <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
          <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
      </form>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-9 mt-3 mb-2">
      <p class="text-center">Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a></p>
    </div>
  </div>

</div>
{% endblock %}